In [1]:
import pandas as pd
import numpy as np


In [2]:
a_C = 0.714
a_A = 23.2
def GetZfromA(A):
    f_A = 1+(a_C/(2*a_A))*np.power(A, 2./3)
    Z = np.divide(A, 1+f_A)
    return np.round(Z).astype(int)
print("A = 142, Z =", GetZfromA(142))

A = 142, Z = 59


In [3]:
A0 = 284
#A1 = np.linspace(80, 208, 7, dtype=int)
A1 = np.linspace(142, 208, 3, dtype=int)
Z1 = GetZfromA(A1)
A2 = A0 - A1
Z2 = GetZfromA(A2)
print("A1:", A1, "Z1:", Z1)
print("A2:", A2, "Z2:", Z2)

A1: [142 175 208] Z1: [59 71 82]
A2: [142 109  76] Z2: [59 46 33]


In [4]:
TKE = 275

In [5]:
A0 = 284

In [6]:
print(A1)
print(A0-A1)
TKE_all = [225] # MeV
for j, TKE in enumerate(TKE_all):
    E1 = np.divide(TKE, 1+np.divide(A1, A0-A1))
    E2 = TKE - E1 
    print("Fragment 1 kinetic energy:", E1, "MeV")
    print("Fragment 2 kinetic energy:", E2, "MeV")

[142 175 208]
[142 109  76]
Fragment 1 kinetic energy: [112.5         86.3556338   60.21126761] MeV
Fragment 2 kinetic energy: [112.5        138.6443662  164.78873239] MeV


In [7]:
cols = ["TKE", "A1", "A2", "E1", "E2", "Z1", "Z2"]
df_energies = pd.DataFrame(columns=cols)
df_energies

Empty DataFrame
Columns: [TKE, A1, A2, E1, E2, Z1, Z2]
Index: []

In [8]:
TKE_all = [225, 250, 275] # MeV
print(A1)
A2 = A0-A1
print(A2)
for j, TKE in enumerate(TKE_all):
    E1 = np.divide(TKE, 1+np.divide(A1, A2))
    E2 = TKE - E1 
    for k, E1_k in enumerate(E1):
        df_energies = df_energies.append({'TKE': TKE, 'A1': A1[k], 'A2': A2[k], 'E1': E1_k, 'E2': E2[k], 'Z1':  GetZfromA(A1[k]), 'Z2': 112 - GetZfromA(A1[k])}, ignore_index=True)
    print("Fragment 1 kinetic energy:", E1, "MeV")
    print("Fragment 2 kinetic energy:", E2, "MeV")

[142 175 208]
[142 109  76]
Fragment 1 kinetic energy: [112.5         86.3556338   60.21126761] MeV
Fragment 2 kinetic energy: [112.5        138.6443662  164.78873239] MeV
Fragment 1 kinetic energy: [125.          95.95070423  66.90140845] MeV
Fragment 2 kinetic energy: [125.         154.04929577 183.09859155] MeV
Fragment 1 kinetic energy: [137.5        105.54577465  73.5915493 ] MeV
Fragment 2 kinetic energy: [137.5        169.45422535 201.4084507 ] MeV


In [9]:
df_energies

TKE     A1     A2          E1          E2    Z1    Z2
0  225.0  142.0  142.0  112.500000  112.500000  59.0  53.0
1  225.0  175.0  109.0   86.355634  138.644366  71.0  41.0
2  225.0  208.0   76.0   60.211268  164.788732  82.0  30.0
3  250.0  142.0  142.0  125.000000  125.000000  59.0  53.0
4  250.0  175.0  109.0   95.950704  154.049296  71.0  41.0
5  250.0  208.0   76.0   66.901408  183.098592  82.0  30.0
6  275.0  142.0  142.0  137.500000  137.500000  59.0  53.0
7  275.0  175.0  109.0  105.545775  169.454225  71.0  41.0
8  275.0  208.0   76.0   73.591549  201.408451  82.0  30.0

In [10]:
df_energies.set_index(['TKE', 'A1', 'A2'],inplace=True)

In [11]:
df_energies

E1          E2    Z1    Z2
TKE   A1    A2                                       
225.0 142.0 142.0  112.500000  112.500000  59.0  53.0
      175.0 109.0   86.355634  138.644366  71.0  41.0
      208.0 76.0    60.211268  164.788732  82.0  30.0
250.0 142.0 142.0  125.000000  125.000000  59.0  53.0
      175.0 109.0   95.950704  154.049296  71.0  41.0
      208.0 76.0    66.901408  183.098592  82.0  30.0
275.0 142.0 142.0  137.500000  137.500000  59.0  53.0
      175.0 109.0  105.545775  169.454225  71.0  41.0
      208.0 76.0    73.591549  201.408451  82.0  30.0

In [18]:
df_energies.loc[225,175,109] 

E1     86.355634
E2    138.644366
Z1     71.000000
Z2     41.000000
Name: (225.0, 175.0, 109.0), dtype: float64